language: php

php:
  - '7.1'
  - '7.2'
  - nightly

before_install:
- composer install --dev
 
script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml --configuration phpunit-travis.xml